### ISSUE TITLE
alpha checklist

### ISSUE THREAD

**Issue by noahehall** [nirv-ai/docs#17]
- [ ] ci in place
- [ ] cd in place
- [ ] authnz on test.nirv.ai
- [ ] completely immutable infrastructure, from dev to prod
